### PR TITLE
Notifications + Docker + misc

### PR DESCRIPTION
**Pull request by tripleee**
This is just a very dirty merge, if you like I can try to create branches and clean this up into three or four separate pull requests.

The dockerize work should be easy to separate out, it just creates some auxiliary files to help make a Docker image.

The notifications are what I worked on recently, though a couple of recent Docker changes were necessary to bring everything into shape.

Again, feel free to reject this if you think it's too messy.

### CODE REVIEW

**Comment by double-fault** [comment]
Thanks for adding the notifications! That seems like a useful feature.

I'll leave the docker stuff to you as I don't really have any experience there. I'll just quickly go over the code ASAP, then I'll merge.

Also, you've got write access, so you can directly push. I can move this repository to Charcoal-SE if you want.

**Comment by double-fault** [comment]
Hmm, seems all fine! I'm assuming this all is working and tested.

**Comment by tripleee** [comment]
It's up and running, yes. I tried to push but it failed, maybe I had the wrong key or something. Thanks for the merge!

**Comment by tripleee** [comment]
Re: moving to Charcoal, I'm kind of divided. This component doesn't make sense in isolation and Halflife isn't necessarily ready to become a community project yet. But perhaps I should just move it there anyway.

**Pull request merged**
